### ISSUE TITLE
Suggestions - GitHub Actions

### ISSUE THREAD

**Issue by ghost** [szeweq/mc-repack#1]
I have a suggestion which would be useful for me and perhaps for other creators:

- Create a GitHub Action.

I am currently having to use the following combination:
```
- name: Install tools
  uses: baptiste0928/cargo-install@v2.1.0
  with:
    crate: mc-repack
- name: Clean files
  run: mc-repack "/home/runner/work/[repository-name]/[repository-name]/build/libs/" --out "/home/runner/work/[repository-name]/[repository-name]/build/libs/clean/"
```
Note:
  1. I have to include full path.
  3. I can't use a environment variable.

If there is anything I can do to help, let me know.
